"""empty message

Revision ID: 238b01b39016
Revises: 
Create Date: 2020-05-16 20:49:26.533634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '238b01b39016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('hall',
    sa.Column('hall_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('num_of_seats', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('hall_id'),
    sa.UniqueConstraint('hall_id')
    )
    op.create_table('movie',
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=80), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('age_category', sa.String(length=40), nullable=True),
    sa.Column('movie_category', sa.String(length=80), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id'),
    sa.UniqueConstraint('movie_id')
    )
    op.create_table('seance',
    sa.Column('seance_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hall_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tickets_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.hall_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], ),
    sa.PrimaryKeyConstraint('seance_id'),
    sa.UniqueConstraint('seance_id')
    )
    op.create_table('seat',
    sa.Column('seat_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.hall_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('seat_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('seance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seance_id'], ['seance.seance_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.seat_id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('seat')
    op.drop_table('seance')
    op.drop_table('movie')
    op.drop_table('hall')
    op.drop_table('employee')
    # ### end Alembic commands ###
