"""empty message

Revision ID: 2dd256b31737
Revises: 83709f7fcfea
Create Date: 2020-05-10 22:29:36.331228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd256b31737'
down_revision = '83709f7fcfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_value2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_value', name='test_pkey')
    )
    # ### end Alembic commands ###
