"""empty message

Revision ID: 34226b3f38c5
Revises: d709d6b235ff
Create Date: 2020-04-27 20:22:23.003855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34226b3f38c5'
down_revision = 'd709d6b235ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
