"""empty message

Revision ID: 3ac4e977c037
Revises: 6c8f7a7718f1
Create Date: 2020-05-17 21:56:02.134558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac4e977c037'
down_revision = '6c8f7a7718f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall', sa.Column('seats_per_row', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hall', 'seats_per_row')
    # ### end Alembic commands ###
