"""empty message

Revision ID: 4a6c012f67e8
Revises: 3ac4e977c037
Create Date: 2020-05-17 22:59:18.744141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6c012f67e8'
down_revision = '3ac4e977c037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seat_hall_id_fkey', 'seat', type_='foreignkey')
    op.create_foreign_key(None, 'seat', 'hall', ['hall_id'], ['hall_id'])
    op.create_unique_constraint('unique_ticket_seat_and_seance', 'ticket', ['seat_id', 'seance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ticket_seat_and_seance', 'ticket', type_='unique')
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.create_foreign_key('seat_hall_id_fkey', 'seat', 'hall', ['hall_id'], ['hall_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
