"""empty message

Revision ID: 6c8f7a7718f1
Revises: 377b75bd4ff9
Create Date: 2020-05-17 21:01:25.541931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c8f7a7718f1'
down_revision = '377b75bd4ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('close_date', sa.Date(), nullable=True))
    op.drop_column('movie', 'availability')
    op.alter_column('seance', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('seance', 'time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seance', 'time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('seance', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('movie', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'close_date')
    # ### end Alembic commands ###
