"""empty message

Revision ID: 83709f7fcfea
Revises: c241feb9843b
Create Date: 2020-05-10 20:37:47.269313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83709f7fcfea'
down_revision = 'c241feb9843b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_value2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_value', name='test_pkey')
    )
    # ### end Alembic commands ###
